#!/usr/bin/env python3
"""WizardKit: Build UFD Tool"""
# vim: sts=2 sw=2 ts=2

import wk


if __name__ == '__main__':
  try:
    wk.kit.ufd.build_ufd()
  except SystemExit:
    raise
  except: #pylint: disable=bare-except
    wk.std.major_exception()
