#!/bin/bash
#
## WizardKit: ddrescue TUI Launcher

__OS_NAME="$(uname -s)"
if [[ "$__OS_NAME" == "Darwin" ]]; then
  __OS_NAME="macOS"
fi
__NOTICE="This script is not fully supported under $__OS_NAME!

Limitations:
    Map files are saved to a RAM disk so you can't resume after a restart.
    Only whole devices are supported.

Press Enter to continue..."

# Check if running under Linux
if [[ "$__OS_NAME" != "Linux" ]]; then
  echo "${__NOTICE}"
  read -r _dontcare
fi

source launch-in-tmux

SESSION_NAME="ddrescue-tui"
WINDOW_NAME="ddrescue TUI"
TMUX_CMD="ddrescue-tui.py"

launch_in_tmux "$@"
