#!/bin/bash
#
## WizardKit: Update pacman settings to usage in live sessions

# Disable custom repo (used at build-time)
sudo sed -i -r "s/^(\[custom\])/#\1/" /etc/pacman.conf
sudo sed -i -r "s/^(SigLevel = Optional TrustAll)/#\1/" /etc/pacman.conf
sudo sed -i -r "s/^(Server = )/#\1/" /etc/pacman.conf

# Disable signature checks
sudo sed -i -r "s/^SigLevel.*/SigLevel = Never/" /etc/pacman.conf

# Init Pacman keyring
sudo systemctl start pacman-init.service

# Refresh package databases
sudo pacman -Sy

