#!/bin/bash
#
## Wizard Kit: HW Diagnostics - Audio

# Unmute and set volume
amixer -q set "Master" 80% unmute
amixer -q set "PCM" 90% unmute

speaker-test -c 2 -l 1 -t pink
# speaker-test -c 2 -l 1 -t sine
speaker-test -c 2 -l 1 -t wav

