#!/bin/bash
#
## Wizard Kit: HW Diagnostics - Prime95

function usage {
    echo "Usage: $0 log-dir"
    echo "  e.g. $0 /tmp/tmp.7Mh5f1RhSL9001"
}

# Bail early
if [ ! -d "$1" ]; then
    usage
    exit 1
fi

# Run Prime95
mprime -t | grep -iv --line-buffered 'stress.txt' | tee -a "$1/prime.log"
