#!/bin/python3
#
## Wizard Kit: HW Diagnostics - Menu

import os
import sys

# Init
os.chdir(os.path.dirname(os.path.realpath(__file__)))
sys.path.append(os.getcwd())
from functions.hw_diags import *
from functions.tmux import *
init_global_vars()

if __name__ == '__main__':
  # Show menu
  try:
    state = State()
    menu_diags(state, sys.argv)
  except KeyboardInterrupt:
    print_standard(' ')
    print_warning('Aborted')
    print_standard(' ')
    sleep(1)
    pause('Press Enter to exit...')
  except SystemExit:
    # Normal exit
    pass
  except:
    tmux_kill_all_panes()
    major_exception()

  # Done
  tmux_kill_all_panes()
  exit_script()

# vim: sts=2 sw=2 ts=2
