#!/bin/python3
#
## Wizard Kit: Sensor monitoring tool

import os
import sys

# Init
os.chdir(os.path.dirname(os.path.realpath(__file__)))
sys.path.append(os.getcwd())
from functions.sensors import *
from functions.tmux import *
init_global_vars()

if __name__ == '__main__':
  try:
    result = run_program(['mktemp'])
    monitor_file = result.stdout.decode().strip()
    print(monitor_file)
    monitor_pane = tmux_split_window(
      percent=1, vertical=True, watch=monitor_file)
    cmd = ['tmux', 'resize-pane', '-Z', '-t', monitor_pane]
    run_program(cmd, check=False)
    monitor_sensors(monitor_pane, monitor_file)
    exit_script()
  except SystemExit:
    pass
  except:
    major_exception()

# vim: sts=2 sw=2 ts=2
