#!/bin/python3
#
## Wizard Kit: Backup share mount tool

import os
import sys

# Init
sys.path.append(os.path.dirname(os.path.realpath(__file__)))
from functions.data import *
from functions.network import *
init_global_vars()

if __name__ == '__main__':
  try:
    # Prep
    clear_screen()

    # Connect
    connect_to_network()

    # Mount
    if is_connected():
      mount_backup_shares(read_write=True)
    else:
      # Couldn't connect
      print_error('ERROR: No network connectivity.')

    # Done
    print_standard('\nDone.')
    #pause("Press Enter to exit...")
    exit_script()
  except SystemExit as sys_exit:
    exit_script(sys_exit.code)
  except:
    major_exception()

# vim: sts=2 sw=2 ts=2
