# Wizard Kit: Settings - Sources

SOURCE_URLS = {
    'NotepadPlusPlus': 'https://notepad-plus-plus.org/repository/7.x/7.5.1/npp.7.5.1.bin.minimalist.7z',
    'TestDisk': 'https://www.cgsecurity.org/testdisk-7.1-WIP.win.zip',
    'FastCopy32': 'http://ftp.vector.co.jp/69/28/2323/FastCopy332.zip',
    'FastCopy64': 'http://ftp.vector.co.jp/69/28/2323/FastCopy332_x64.zip',
    'XYplorerFree': 'https://www.xyplorer.com/download/xyplorer_free_noinstall.zip',
    'AIDA64': 'http://download.aida64.com/aida64engineer592.zip',
    'Autoruns': 'https://download.sysinternals.com/files/Autoruns.zip',
    'BleachBit': 'https://download.bleachbit.org/beta/1.17/BleachBit-1.17-portable.zip',
    'Winapp2': 'https://github.com/MoscaDotTo/Winapp2/archive/master.zip',
    'BlueScreenView32': 'http://www.nirsoft.net/utils/bluescreenview.zip',
    'BlueScreenView64': 'http://www.nirsoft.net/utils/bluescreenview-x64.zip',
    'Du': 'https://download.sysinternals.com/files/DU.zip',
    'ERUNT': 'http://www.aumha.org/downloads/erunt.zip',
    'HitmanPro32': 'https://dl.surfright.nl/HitmanPro.exe',
    'HitmanPro64': 'https://dl.surfright.nl/HitmanPro_x64.exe',
    'HWiNFO32': 'http://app.oldfoss.com:81/download/HWiNFO/hw32_560.zip',
    'HWiNFO64': 'http://app.oldfoss.com:81/download/HWiNFO/hw64_560.zip',
    'ProduKey32': 'http://www.nirsoft.net/utils/produkey.zip',
    'ProduKey64': 'http://www.nirsoft.net/utils/produkey-x64.zip',
    'Intel SSD Toolbox': r'https://downloadmirror.intel.com/27330/eng/Intel%20SSD%20Toolbox%20-%20v3.4.9.exe',
    'Samsung Magician': 'http://downloadcenter.samsung.com/content/SW/201710/20171019164455812/Samsung_Magician_Installer.exe',
    'aria2': 'https://github.com/aria2/aria2/releases/download/release-1.33.1/aria2-1.33.1-win-32bit-build1.zip',
    'SDIO Torrent': 'http://snappy-driver-installer.org/downloads/SDIO_Update.torrent',
    'SDIO Themes': 'http://snappy-driver-installer.org/downloads/SDIO_Themes.zip',
    'Adobe Reader DC': 'http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1800920044/AcroRdrDC1800920044_en_US.exe',
    'Everything32': 'https://www.voidtools.com/Everything-1.4.1.877.x86.zip',
    'Everything64': 'https://www.voidtools.com/Everything-1.4.1.877.x64.zip',
    'TreeSizeFree-Portable': 'https://www.jam-software.com/treesize_free/TreeSizeFree-Portable.zip',
    'XMPlay': 'http://support.xmplay.com/files/20/xmplay3823.zip?v=115916',
    'XMPlay 7z': 'http://support.xmplay.com/files/16/xmp-7z.zip?v=800962',
    'XMPlay Game': 'http://support.xmplay.com/files/12/xmp-gme.zip?v=515637',
    'XMPlay RAR': 'http://support.xmplay.com/files/16/xmp-rar.zip?v=409646',
    'XMPlay WAModern': 'http://support.xmplay.com/files/10/WAModern.zip?v=207099',
    'AdwCleaner': 'https://toolslib.net/downloads/finish/1-adwcleaner/',
    'KVRT': 'http://devbuilds.kaspersky-labs.com/devbuilds/KVRT/latest/full/KVRT.exe',
    'RKill': 'https://www.bleepingcomputer.com/download/rkill/dl/10/',
    'TDSSKiller': 'https://media.kaspersky.com/utilities/VirusUtilities/EN/tdsskiller.exe',
    'IOBit_Uninstaller': 'https://portableapps.com/redirect/?a=IObitUninstallerPortable&t=http%3A%2F%2Fdownloads.portableapps.com%2Fportableapps%2Fiobituninstallerportable%2FIObitUninstallerPortable_7.0.2.49.paf.exe',
    }
NINITE_SOURCES = {
    'Bundles': {
        'Runtimes.exe': '.net4.7-air-java8-silverlight',
        'Legacy.exe': '.net4.7-7zip-air-chrome-firefox-java8-silverlight-vlc',
        'Modern.exe': '.net4.7-7zip-air-chrome-classicstart-firefox-java8-silverlight-vlc',
        },
    'Audio-Video': {
        'AIMP.exe': 'aimp',
        'Audacity.exe': 'audacity',
        'CCCP.exe': 'cccp',
        'Foobar2000.exe': 'foobar',
        'GOM.exe': 'gom',
        'HandBrake.exe': 'handbrake',
        'iTunes.exe': 'itunes',
        'K-Lite Codecs.exe': 'klitecodecs',
        'MediaMonkey.exe': 'mediamonkey',
        'MusicBee.exe': 'musicbee',
        'Spotify.exe': 'spotify',
        'VLC.exe': 'vlc',
        'Winamp.exe': 'winamp',
        },
    'Cloud Storage': {
        'Dropbox.exe': 'dropbox',
        'Google Backup & Sync.exe': 'googlebackupandsync',
        'Mozy.exe': 'mozy',
        'OneDrive.exe': 'onedrive',
        'SugarSync.exe': 'sugarsync',
        },
    'Communication': {
        'Pidgin.exe': 'pidgin',
        'Skype.exe': 'skype',
        'Trillian.exe': 'trillian',
        },
    'Compression': {
        '7-Zip.exe': '7zip',
        'PeaZip.exe': 'peazip',
        'WinRAR.exe': 'winrar',
        },
    'Developer': {
        'Eclipse.exe': 'eclipse',
        'FileZilla.exe': 'filezilla',
        'JDK 8.exe': 'jdk8',
        'JDK 8 (x64).exe': 'jdkx8',
        'Notepad++.exe': 'notepadplusplus',
        'PuTTY.exe': 'putty',
        'Python 2.exe': 'python',
        'Visual Studio Code.exe': 'vscode',
        'WinMerge.exe': 'winmerge',
        'WinSCP.exe': 'winscp',
        },
    'File Sharing': {
        'qBittorrent.exe': 'qbittorrent',
        },
    'Image-Photo': {
        'Blender.exe': 'blender',
        'FastStone.exe': 'faststone',
        'GIMP.exe': 'gimp',
        'Greenshot.exe': 'greenshot',
        'Inkscape.exe': 'inkscape',
        'IrfanView.exe': 'irfanview',
        'Krita.exe': 'krita',
        'Paint.NET.exe': 'paint.net',
        'ShareX.exe': 'sharex',
        'XnView.exe': 'xnview',
        },
    'Misc': {
        'Evernote.exe': 'evernote',
        'Everything.exe': 'everything',
        'KeePass 2.exe': 'keepass2',
        'Google Earth.exe': 'googleearth',
        'NV Access.exe': 'nvda',
        'Steam.exe': 'steam',
        },
    'Office': {
        'CutePDF.exe': 'cutepdf',
        'Foxit Reader.exe': 'foxit',
        'LibreOffice.exe': 'libreoffice',
        'OpenOffice.exe': 'openoffice',
        'PDFCreator.exe': 'pdfcreator',
        'SumatraPDF.exe': 'sumatrapdf',
        'Thunderbird.exe': 'thunderbird',
        },
    'Runtimes': {
        'Adobe Air.exe': 'air',
        'dotNET.exe': '.net4.7',
        'Java 8.exe': 'java8',
        'Shockwave.exe': 'shockwave',
        'Silverlight.exe': 'silverlight',
        },
    'Security': {
        'Avast.exe': 'avast',
        'AVG.exe': 'avg',
        'Avira.exe': 'avira',
        'Microsoft Security Essentials.exe': 'essentials',
        'Malwarebytes Anti-Malware.exe': 'malwarebytes',
        'Spybot 2.exe': 'spybot2',
        'SUPERAntiSpyware.exe': 'super',
        },
    'Utilities': {
        'CDBurnerXP.exe': 'cdburnerxp',
        'Classic Start.exe': 'classicstart',
        'Glary Utilities.exe': 'glary',
        'ImgBurn.exe': 'imgburn',
        'InfraRecorder.exe': 'infrarecorder',
        'Launchy.exe': 'launchy',
        'RealVNC.exe': 'realvnc',
        'Revo Uninstaller.exe': 'revo',
        'TeamViewer 12.exe': 'teamviewer12',
        'TeraCopy.exe': 'teracopy',
        'WinDirStat.exe': 'windirstat',
        },
    'Web Browsers': {
        'Google Chrome.exe': 'chrome',
        'Mozilla Firefox.exe': 'firefox',
        'Opera Chromium.exe': 'operaChromium',
        },
    }
RST_SOURCES = {
    #SetupRST_12.0.exe :  Removed from download center?
    #SetupRST_12.5.exe :  Removed from download center?
    #SetupRST_12.8.exe :  Removed from download center?
    'SetupRST_12.9.exe': 'https://downloadmirror.intel.com/23496/eng/SetupRST.exe',
    #SetupRST_13.x.exe :  Broken, doesn't support > .NET 4.5
    'SetupRST_14.0.exe': 'https://downloadmirror.intel.com/25091/eng/SetupRST.exe',
    'SetupRST_14.8.exe': 'https://downloadmirror.intel.com/26759/eng/setuprst.exe',
    'SetupRST_15.8.exe': 'https://downloadmirror.intel.com/27147/eng/SetupRST.exe',
    }


if __name__ == '__main__':
    print("This file is not meant to be called directly.")
