# Wizard Kit: Settings - Windows Builds

WINDOWS_BUILDS = {
#   Build       Version     Release     Codename        Marketing Name          Notes
     '6000': (  'Vista',    'RTM',      'Longhorn',     None,                   'unsupported'),
     '6000': (  'Vista',    'RTM',      'Longhorn',     None,                   'unsupported'),
     '6001': (  'Vista',    'SP1',      'Longhorn',     None,                   'unsupported'),
     '6002': (  'Vista',    'SP2',      'Longhorn',     None,                   'unsupported'),

     '7600': (  '7',        'RTM',      'Vienna',       None,                   'unsupported'),
     '7601': (  '7',        'SP1',      'Vienna',       None,                   'outdated'),

     #9199 is a fake build since Win 8 is 6.2.9200 but that collides with Win 8.1 (6.3.9200)
     '9199': (  '8',        'RTM',      None,           None,                   'unsupported'),

     '9200': (  '8.1',      None,       'Blue',         None,                   'outdated'),
     '9600': (  '8.1',      None,       'Update',       None,                   None),

     '9841': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
     '9860': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
     '9879': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
     '9926': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10041': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10049': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10061': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10074': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10122': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10130': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10158': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10159': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10162': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10166': (  '10',       None,       'Threshold 1',  None,                   'preview build'),
    '10240': (  '10',       'v1507',    'Threshold 1',  None,                   'unsupported'),
    '10525': (  '10',       None,       'Threshold 2',  None,                   'preview build'),
    '10532': (  '10',       None,       'Threshold 2',  None,                   'preview build'),
    '10547': (  '10',       None,       'Threshold 2',  None,                   'preview build'),
    '10565': (  '10',       None,       'Threshold 2',  None,                   'preview build'),
    '10576': (  '10',       None,       'Threshold 2',  None,                   'preview build'),
    '10586': (  '10',       'v1511',    'Threshold 2',  'November Update',      'unsupported'),
    '11082': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '11099': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '11102': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14251': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14257': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14271': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14279': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14291': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14295': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14316': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14328': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14332': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14342': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14352': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14361': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14366': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14367': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14371': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14372': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14376': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14379': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14383': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14385': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14388': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14390': (  '10',       None,       'Redstone 1',   None,                   'preview build'),
    '14393': (  '10',       'v1607',    'Redstone 1',   'Anniversary Update',   'unsupported'),
    '14901': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14905': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14915': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14926': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14931': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14936': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14942': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14946': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14951': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14955': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14959': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14965': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14971': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '14986': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15002': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15007': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15014': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15019': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15025': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15031': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15042': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15046': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15048': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15055': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15058': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15060': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15061': (  '10',       None,       'Redstone 2',   None,                   'preview build'),
    '15063': (  '10',       'v1703',    'Redstone 2',   'Creators Update',      'outdated'),
    '16170': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16176': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16179': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16184': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16188': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16193': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16199': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16212': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16215': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16226': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16232': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16237': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16241': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16251': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16257': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16273': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16275': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16278': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16281': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16288': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16291': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16294': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16296': (  '10',       None,       'Redstone 3',   None,                   'preview build'),
    '16299': (  '10',       'v1709',    'Redstone 3',   'Fall Creators Update', 'outdated'),
    '16353': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '16362': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17004': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17017': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17025': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17035': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17040': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17046': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17063': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17074': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17083': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17093': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17101': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17107': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17110': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17112': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17115': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17120': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17123': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17127': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17128': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17133': (  '10',       None,       'Redstone 4',   None,                   'preview build'),
    '17134': (  '10',       'v1803',    'Redstone 4',   'April 2018 Update',    None),
    '17604': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17618': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17623': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17627': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17634': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17639': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17643': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17650': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17655': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17661': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17666': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17677': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17682': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17686': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17692': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17704': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17711': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17713': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17723': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17728': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17730': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17733': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17735': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17738': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17741': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17744': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17746': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17751': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17754': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17755': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17758': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17760': (  '10',       None,       'Redstone 5',   None,                   'preview build'),
    '17763': (  '10',       'v1809',    'Redstone 5',   'October 2018 Update',  'preview build'),
    '18204': (  '10',       None,       '19H1',         None,                   'preview build'),
    '18214': (  '10',       None,       '19H1',         None,                   'preview build'),
    '18219': (  '10',       None,       '19H1',         None,                   'preview build'),
    '18234': (  '10',       None,       '19H1',         None,                   'preview build'),
    '18237': (  '10',       None,       '19H1',         None,                   'preview build'),
    '18242': (  '10',       None,       '19H1',         None,                   'preview build'),
    '18247': (  '10',       None,       '19H1',         None,                   'preview build'),
    '18252': (  '10',       None,       '19H1',         None,                   'preview build'),
}

if __name__ == '__main__':
    print("This file is not meant to be called directly.")
